### ISSUE TITLE
dde-extra/deepin-voice-note

### ISSUE THREAD

**Issue by jairao** [linuxdeepin/deepin-voice-note#1]
Good night! I have a problem with the dde-extra / deepin-voice-note package, it is not downloading from the links https://github.com/linuxdeepin/deepin-voice-note/archive/5.7.8.tar.gz and https: //github.com/linuxdeepin/deepin-voice-note/archive/5.7.8.tar.gz this and in the gentoo distribution the error is 404.

**Comment by V4fr3e** [comment]
@jairao hi, you may reference the tag in the old version project:  https://github.com/linuxdeepin/deepin-voice-note-old/tags.

**Comment by jairao** [comment]
Good night! I searched but I can't get portage to find the new address if you can help me how you do it or refer me to a specific gentoo website or documentation. I appreciate your help.

**Comment by V4fr3e** [comment]
@jairao new repository:  https://github.com/linuxdeepin/deepin-voice-note, you can clone the project , and check out to the tag you want , then build it.

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
