### ISSUE TITLE
I cannot create new directory

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/deepin-voice-note#4]
When I firstly running this program (see screenshot), I received this error:
```
 0] Add folder failded: New folder: -1 Name: "" Create time: QDateTime(Invalid) Modify time: QDateTime(Invalid)
```
![Captura de pantalla_2020-08-21_18-35-32](https://user-images.githubusercontent.com/89915/90913852-1e121300-e3dd-11ea-9fdd-9ef99768be1a.png)

**Comment by z966768** [comment]
please try the newest version

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
