### ISSUE TITLE
Nothing works...

### ISSUE THREAD

**Issue by tiotrom** [linuxdeepin/deepin-voice-note#5]
I am using Manjaro Gnome and I can only open this app, but nothing works....to create a new notebook, to record, to change the theme...I click and nothing happens...

**Comment by felixonmars** [comment]
Deepin apps are intended only for DDE at this time. GNOME is currently unsupported.

**Comment by tiotrom** [comment]
I see. Ok. Thanks

**Comment by z966768** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
